[package]
name = "inkbird-ibt"
version = "0.1.0"
authors = ["Andre Masella <andre@masella.name>"]
edition = "2018"

[dependencies]
actix-web = "1.0.5"
blurz = "0.4.0"
byteorder = "1"
clap = "2.33.0"
ctrlc = "3.1.3"
prometheus = "0.7.0"
